### ISSUE TITLE
Session management in cluster

### ISSUE THREAD

**Issue by Seshaega** [TIBCOSoftware/js-docker#26]
Hi, If multiple pods are running with jasper server, and cloud does not support sticky session, and consequent requests will go to the different pods, where the HTTP Session is invalid, and route me back to login page. Is there any configuration for disabling or enabling the session.

Thanks
Seshaa

**Comment by sgwood63** [comment]
JasperReports Server requires sticky sessions when working with a load balancer.

As we document in the JasperReports Server Ultimate Guide "Designing a cluster" on https://community.jaspersoft.com/documentation, there is also the need to replicate internal caches across the cluster so that data updates to the repository - new reports, say - are consistent across the machines in the cluster. The Ultimate Guide documents a few different cache replication approaches, depending on the deployment architecture.

What load balancer are you using in your cloud? All load balancers I know of support sticky sessions or "session affinity".

Leaving this open for now. I can provide a load balancer configurations for haproxy and EKS that support JasperReports Server.

**Comment by sgwood63** [comment]
I have added an example set up of a JasperReports Server cluster in containers. It uses JMS.
