### ISSUE TITLE
Question about if/ else statement

### ISSUE THREAD

**Issue by dorothythurston** [TIBCOSoftware/js-docker#9]
Hello! This is less of an issue and more of a question... I am refactoring my entrypoint.sh script in my own repo and I was wondering why is this if/else statement necessary: https://github.com/TIBCOSoftware/js-docker/blob/master/scripts/entrypoint.sh#L77 It looks like both options end up being  setup_jasperserver deploy-webapp-pro ? Am I misreading this code? Thank you for your time!

**Comment by jeffallen** [comment]
That code says, "if webapps/jasperserver-pro is already present, BUT things are not totally installed, then install the app. otherwise, since webapps/jasperserver-pro is not present, always install the app."

The comment above says it "makes it faster". IMHO, when you see "makes it faster" and then hairy code underneath it, that's a code smell, and you are right to look twice at this. But I don't see any problem here, other than this confusing code.

**Comment by nataliiakel** [comment]
Will close an issue since.
